- name: Install and update apt packages
  hosts: localhost
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install apt packages
      apt:
        name:
          - git
          - curl
          - zsh
          - alacritty
        state: latest

    # - name: Install Starship prompt

    - name: Install oh-my-zsh
      shell: >
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
