- name: Update
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install apt packages
      apt:
        name:
          - zsh
          - curl
        state: latest
